apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    targetRevision: 20.8.0
    helm:
      values: |
        # ваши настройки traefik, например:
        # ingressClass:
        #   name: traefik
        #   enabled: true
        # ports:
        #   web:
        #     redirectTo: websecure
        #   websecure:
        #     tls:
        #       enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
