---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mtproxy-config
  namespace: mtproxy
spec:
  encryptedData:
    config.toml: AgDb3wIi8IpwfM3HeDEiqo+LqopcZxOknzTXKGiNkX+PaC7WBq/FxgInhGTWYP6KWVSE0zUPPca3iRpO8ncrb2V6NEEzuDi8jzYoufaAdNUyNEGS/Rh1gMJ/3q4JdXrvVusqpHN2oAmW4YVeosiI79EQTkAfnkmgqKrbzP11+bwNvZuhpg6zgswJ/jU8oHxYEt386vvu/afABOk3FLTer+D8Ob4lYCovRIluAPpNyMXQ3U4WRkuTPLEzQkvCf46oeFReefWc2ghMmiTrgp3nBQ9QMwd/+xeQd6veFEHuzT0IqgV9SbVQn7RBEvR8tPrVndPo5FFsjWA6o0qWM9FiNFAUBKIT0/bm69ERyeNKLJHvowhPW6iotU6dk6vAu2hdMTmtkHWCK+NW5/869vWwayXw1qJMoxbPlQCV9jzueBKMUOaOyfuREfpnZgUZI9n/XKlzCWol+w+4xwHU74D2I79EZUzg/NaMlH/nfw3vCHLISVxmW+9LRZVENUo6ED+4h1XNmj7KL2a+O8PSRuwEUoeEFL6WxYBwHKxuMEB7k3mxVCh3JCoqvPLX2UnozR7ZBfQFWTCiQMQBU5y+4jCxbbNSl7zuXNsCuUpMigu3+GenpLUwi3PSrFAZc32sAPhZOtWLM/XDADfa1Rd83zji+dyGoWfPJGVVS6IwfDGLCPhkZ4uQPvnjdkTFCVs7jb043St+HyfKPsW0nO/jdNz/2HdraGEkS7SDtOf+6CP+r1YSonjdgz+nFEHuSGiKIn5cagJ7V+3vZEXEqKHG6uNvKY1Ay0CojeJBs89sxrMrKf4thGEyrL8Y7xHFVhR9ewqamF9wskw=
  template:
    metadata:
      creationTimestamp: null
      name: mtproxy-config
      namespace: mtproxy