---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mtproxy-config
  namespace: mtproxy
spec:
  encryptedData:
    config.toml: AgA2DkcGEjIRD4fb9jSCYLCQ4+aYKwaJQf65QN5sMLHSZ+1A93XSyXegmbkdgfilOLBESOZoN5P7pXkDxiTDzAHp58kCp9ZWQe2QulP7fODaYz8exlJ7YPk4k+pOf6ojfmsnSIxI1Uua6CLUG/4fU501s1xSdY3lGkwZIqCN37GrBKllz5lx/D+TPqxyiLQdQjB0bUJjFFw2Xwi5f3/cN7KDHj0t/bngKXsGA0+8LD/QrjRlcG442mLdh72BquVgQdug7w2iV6Hyw/DcfSWLFvey2+hdgwXtsEiDj5PfM7OdIH8W210loorC2tnvOWd/5zi7/igfUpQWOjIjXYfnBj0EF++pWDBTnwA8fXIvS3OcRAVdBoeOb1EnbyuYLwQdNiJsq2c8Hxt97fLL/Q+DdtYDSUi2gq6b4ZO7+phUVDXkMYyDz4GLhvogA6SPeJlgiGDMuZYoSoFnWvkZQc0xbR8ofyAtYdpkLlqk2+8tj7MBX6WaGZa8EZ6xCDFXeCnKRPcf/LoPjiQsU/kkK4y/BaSvcW4VpEZVo1O+p+A85xb2OrAljna6oSK+hexD3LiPHQvwkWU/3+xGNBvN5J+qE4cz1Vbo9H+QqLAGVwwk12kjhA7Rno82YcBp+bNtVpxVsiuV1Pr9w02k/PSfuOIKo9NAPxiSnQ4Xu338bYYgW6TAAqCKuzxYCiSBUh8Ng8neCU39NL5/7/Z1ReukB64aZLuwettUAj0qhj0MYyl5AxNqGQ6QyOSe61EhCuhqUV7i4XKWP+wkhVdzJQmyKqyQoniMhLdQvY3ferNVtedJUEvrMLvw+Pm3GIXZfyMQqqHZP7VrWBarr/ziKmnDLAJoXUwn2el1O1jbE5kyoO59x2yWhzeTJKJJAUtU4tJhtD1D0kWl1KcZV0laXJsmZQe51GEPNR4gBbBmjY+U+AV1Mr+n3Tz5Tz5zC7e9CtdZiUHKZjYrql1ddGHFfpbfxrjg0G43XU+HcLshT1UdPDF6mkPv0s0YLmDHUd1blJjidTk51vY2YiH4q8gy+5vmCGTbT4NQoVijUGYBOVMbQ95f2iLR00eMdn4GppyrxC+2hogQPB3Y269GHBbjFgQP16Jbg1Sj4B5IkV5I/7WLmob7U410zS7SJutqLDI+2rrEJnQp6xqHf8lvHI5Zxx2EWffltpaUt8w19Za5qavg7X/eIzDP+80jAndlJdaOuklqsOptpl/K+f0Tv0seQth/zFA6BPWznvojCwGq9osiMmapQj4mac5JRE85QmnksIRx7pmC/gRGqKALYAgUXY9Gl6yJms8Bt9fmhecnh1FKRTXTVjLzWCET80yl/n3QFiT4/1332PkVqBm9vjb1AENOqjwwwKvUV5n9ls+yNHtmOiy8gmWDrEe+igFX4AbBo/LI1jQMMPmoPt8WNq7aJmUDRZtJ5ARhn78IzKnncanuKVbGNjdE04o/4FpSriyWJD75308xrNaP02hlm3yjoVmfq90h3+jlFZTDppy0sNH5drGs/0+8YmYODn5XyNrriBbnssn6AJt1gkaxtN0xCbYXkQVPkzXHQDNOZELeuN69iWxj3PaSudaWhqOUmMqaFAzInur54kN6tlxL4q6qH6dmAFaslq5pIQNl7bU=
  template:
    metadata:
      creationTimestamp: null
      name: mtproxy-config
      namespace: mtproxy
