apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamspeak-data
  namespace: teamspeak
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path 
  resources:
    requests:
      storage: 10Gi