apiVersion: v1
kind: ConfigMap
metadata:
  name: tuwunel-config
  namespace: tuwunel
data:
  tuwunel.toml: |
    [global]
    server_name = "home.onishenko.tk"
    database_path = "/var/lib/tuwunel"
    address = ["0.0.0.0", "::"]
    port = 8008
    allow_registration = false
    registration_shared_secret_file = "/etc/tuwunel/secrets/registration_shared_secret"
    allow_federation = true
    ip_source = "rightmost_x_forwarded_for"
    max_request_size = "50 MiB"
    log = "info"
    grant_admin_to_first_user = false

    [global.tls]
    certs = "/etc/tuwunel/tls/tls.crt"
    key = "/etc/tuwunel/tls/tls.key"
    dual_protocol = true

    [global.well_known]
    client = "https://home.onishenko.tk"
    server = "home.onishenko.tk:8448"
