apiVersion: v1
kind: ConfigMap
metadata:
  name: tuwunel-config
  namespace: tuwunel
data:
  tuwunel.toml: |
    [global]
    server_name = "matrix.aonishchenko.ru"
    database_path = "/var/lib/tuwunel"
    address = ["0.0.0.0", "::"]
    port = 8008
    allow_registration = true
    registration_token_file = "/etc/tuwunel/secrets/registration_token"
    registration_shared_secret_file = "/etc/tuwunel/secrets/registration_shared_secret"
    allow_federation = true
    ip_source = "connect_info"
    max_request_size = "50 MiB"
    log = "info"
    grant_admin_to_first_user = false

    [global.well_known]
    client = "https://matrix.aonishchenko.ru"
    server = "matrix.aonishchenko.ru:8448"