---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: socks5-config
  namespace: socks5-proxy
spec:
  encryptedData:
    gost.yaml: AgBPBZs/ozSej7J7HT6Dx4owkwQ6nnbhWzR9G13Oyp+P7bIAmQKnneP92x5dTT8c40OzLV0wnJazqo3s+icZJJGJRuPYO2UjxU12glaJnfw5YnFAh0ExxJ9KpmiRLNqpP9RioysC5TDJs7INgjpisjX9hMlOARJjM/PwmOIEb0vQkXVGIz2LbT/eaRJTEw5Qbn99wUC4K+lWKJ8VyfubM6CzOWdTb7iV+2anuXQsHMBoSkrZKQoR6xxqKkeah97gUPPFD0ZkcfEG0ojMeafeBC08G/vvjbXRXwsHv7X0VgJeTIid+SQF67bQiP+xVFfgDC65ce/PHRR4GfgmOtt4isH/ggwes5ArCnhe0mUbpgOJR9gBgZIkmF0fc+ILYncyUtGpLz8PT4bGFlYax2RZbmxoNZaICF288vqOQrFHdz6siAERaJ72Y4JfJWSRO88IN5QOHt44wlY2waqN2ZE28HGlATNt2N6rJlvA1KSKNECANHSRXabjIJS/qeIMkreMaOkT/s1/1rvJJWvI51ohxHsqqAf13g1I0tcF/FI+s0dYjhZY5PvFtuSxq19jyPvqFY2bJY7coNggxl5HrQ9wnbp5PvR/6H88mA2zIGzC0SpudEhWXL1twEU+sSunjM5DsKPRARhzCTU2LYuqdNcVr9pp2zTOA4zcMGq44fzLdGN/6Vf9WOzhaKecylJxSl9c1aZP9IagNZarwuQS9Z7pMQV5qaTIbxV+/QxD9LEQ8quvJFwMqw+8emM8/TTswetrsY9CuXN5ZDl/xS//jCPwwNbKuM2DOQtLVLuLqnnjLIs7R/LE0MjOOJW/AnVePESzmZTsd5kC7ZaWY6e2s2z2kcyE3fVFVnC5wNsThkEGuiM7u9I5ZkLGpbLEs9pZnwr1d2SqKTFWxLqrrEJfw01VXBRL91COMvmxsEiHoXyg31ImNcIjyvSyXDuX/Ueowa5ffaP778RTmStys5kD/+BOAI1f7qxojQsbewH539qOrOnv/QpAij5zqxpnDTzLiKbm7qczu2rxfcTdEw824lgSlg==
  template:
    metadata:
      creationTimestamp: null
      name: socks5-config
      namespace: socks5-proxy