---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: socks5-config
  namespace: socks5-proxy
spec:
  encryptedData:
    3proxy.cfg: AgAXcxQevmkDNCO2AQAO9CSpo8gHk/pDRKU1TWzPTgrW5hQSB7nEMi26LKIVJ1FPmL8RTclJpenYZlTb90cWzbQUZkkE07SN22/8JDK88lDAvj+INcXXT0UvmJDl7KlS/bs/N84SFzgD5vpk0ILu/hsFn2jLBpdLInGG3HZ/8/xVW+uw/O92LGogytodFPtxZJnAQ/YtdkN9BXrV5/Hzu+lgQudKcjHfGJUyeuOIAOHEdG0QADHA4NYa89c6ZXpJ5/xtee6hQZuQZjzMFP6iny0LE9sq6RtDHCXdWOt2bOPDSRAVIv02bwK3QwRPOa9FxOZaT92TCc6URka3SCDzpft/XOv7WrdLHPSpkUQTNMj7GydRBWZQ1JWFvy4taKxoYupKCWefMC1cx3Ys7IV2BOIQuo8R8HP1D4PVfbcJW2vTuLuWpGtqUwc8jzxN0it2CQ0VXxEb1ro98mHbB+ZP+ajwV90Id6IfiZBbvLFEntGOYN2SFu4TDTO5+Vy/xCN+fUN5mnTR8WmYAStGCbSkhMYH1RX95+5NM1xfhoSAzqepGnDluLXhoz1mY2MecGif4tIQZz+lPnaYLRKLKVskZuBS+SMDEmQtOfXhPhndq4v3Z8PI6JeRKI4BDNEOrGEf5QGWpGTPt7+9G0Vu3soQr+fi0WZnGgFHyoKDCINJ4ovxgNfU74OiBfCIsEsOX6uk3HTWV5RCHnbPQLbPExpobPc42lK2W+taJ/8QbrcGLMSRZpIepBBF4raP4/dxFgw5qvOevUZYdh9Y6WTJDZ/6gjv8MJo/Fzf5Y5XNoId9Rhq8dzJbRqOJ7ntgykSPj9SFesi8o7t2RYPVSozmH3sRrfMXFlvZJV079M6aKZySRBeGzUy+yuGtEmKdG7Gxeg1EcuXqQnFo2wjNhsVw1eQlaKteI/t1nqF+6d0W9R2Zru0ae+/zRHIildUPrtaYmbgbBQ==
  template:
    metadata:
      creationTimestamp: null
      name: socks5-config
      namespace: socks5-proxy