apiVersion: v1
kind: ConfigMap
metadata:
  name: mtg-config
  namespace: mtg-proxy
data:
  config.toml: |
    bind-to = "0.0.0.0:3128"
    # secret задаётся через переменную окружения MTG_SECRET
    # остальные настройки (статистика, лимиты) можно добавить при необходимости