apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtg
  namespace: mtg-proxy
  labels:
    app: mtg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtg
  template:
    metadata:
      labels:
        app: mtg
    spec:
      containers:
        - name: mtg
          image: nineseconds/mtg:2
          ports:
            - containerPort: 3128
              name: mtproto
          env:
            - name: MTG_SECRET
              valueFrom:
                secretKeyRef:
                  name: mtg-secret
                  key: secret
            - name: MTG_BIND
              value: "0.0.0.0:3128"
            - name: MTG_IP_BLOCKLIST_ENABLED
              value: "false" 
          readinessProbe:
            tcpSocket:
              port: 3128
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3128
            initialDelaySeconds: 15
            periodSeconds: 20