---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mtg-secret
  namespace: mtg-proxy
spec:
  encryptedData:
    secret: AgAqdUgnm5HU/nWJ+XyYJKn0+Cq4wTLDOLzsTN4GWQiGu+CeZLKayuORcvqDp0dGjv3ZE7xars+v1TyWMTxgdPHOyXS15GwTTycTjayYOz9Qatvm1vW5BHO8dbLu+0dsoTyxdU1rs3jSlNt9helgPW8zrNRH9dVai6DRH3RNPGMJvhOafeCS91eSuIVf30iwHi7Gzskk2WW4RlJAvEqC6QSlxh5KdOEL53anQMee3Dhjo4K0mcIq67Ycbg9i0ftM90N23/8T3P9bphbSjh/kU0u6J8ZgLffKen/j/LUWqNjw3E2/tZYDbzKjiy44lM8h2bZZqdsL9QbZsuq0kh4CL/CLM8fTOFaFFybShWAds+Bx1our+7gZ/6kBwL652MBiHwDnEqpf68GG4E5K9EcKwPBzAUVGF3kJ72YKHInF5aMyi6bPgp5VdbKXh5oefkkmMggciKew78tonAvo3puZPdqr/7YWyqRJFWvhN556gqFarEbF6q70j5hX3qBOAYNWDJgHtnurFiVpWjtJKYc0ywNb4fD7y3ZD08DVDZmM5ah0MWt9SpsQcnf2gC2TZAbWCF3SAghz8d5LWgCYtiHWis5C1vHaZLLonqxksdh5UICxk3k22//v0XUiTg2hKJYGPEnFmM/t2Ui+X2rGdtUXV2AdCW9n3p52G3IbhmafB0PgKIQlZRt4cUaREL0cWgLlNwh3+jvYzAzdguSA6Bf1yyv48eYDpo9V5TmMFwJFisp9Ti9+RAjCjmEAYvqf9Y9rFoM4KTTnhlwd69ou+/+sydkO
  template:
    metadata:
      creationTimestamp: null
      name: mtg-secret
      namespace: mtg-proxy