---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCqNlInFlwHpiMOGAVe7LivH/vuexoRtS63qoZvJBawOxXmHLAZOVz3sWlJDHGkj2ESCQPagRM2c7coFyk7eUjOh76KpV8vL1Liw8AnPqT9Fen4oIWsCAyWVIHwcY5+lYPMhedToN0mestQg9TUkkNR5q2gvWaT2lp7fjEjreMy2Lds9VtfYC0Iv6gPS7Kh/gBmJuWFKlkMCMsuylgfffauItXW6GDkn4IGIe1GYWUD6Z8glx2bqXl3gewcimMKNm0SDt48rVgCMHHZcMHcS63m4ZsGZdt1UzZp8FSV4xQCFC+9OyKArc5M8TxxcXHq5ApaNnXzT34bgcjqwSsa2sDWZoWLOcBjsbKSDUCDzKzm3FsdZbfc5YrSopdPDhv5iAKiKpn9dHwISI3mVcO7SkrgD4KUuFU0O6UU9H83JVMBUgmcp+DcDpq+e2fepJNNIbjA+vK9abJyI1DFK0BcSA9ksPkHG003gZLhc4u9qaer9Fo/80HdhKSh+lwQbx5yPvoKz1ewGsfV0wgxiGrC+XpCeVCIOkfQFVVex0uRye8DFsq4NlmNviT7Ff3eZMSWR5gMJ4jYhSGSfkOUbT+5viLoHq7wQgNQ8eLmcAW5ss8o5FpVj0g16jGHzRi28sX1+IPCQKzqQBBaVpNuwT1a6m7PwcGe6hzH90uoODZ9noFS/loafYN6cZIz3f9wMsOHl4ac1fswlXOpZzpn5FL8K5PaHrDAvxJrFQ5FJ32VQpk3kJZ5nMBH3FOZUQJNASPIHDIEWA7mDg==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque