apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: home-infra-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/sacrede-mgn/home-infra.git
        revision: HEAD
        directories:
          - path: kubernetes/apps/*
  template:
    metadata:
      name: '{{ path.basename }}'  
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/sacrede-mgn/home-infra.git
        targetRevision: HEAD
        path: '{{ path.path }}'     
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true