apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager/application.yaml
  - headlamp/application.yaml
  - home-ingress/application.yaml
  - traefik/application.yaml
  - teamspeak/application.yaml  
  - mtproxy/application.yaml
