apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/sacrede-mgn/home-infra.git
    targetRevision: HEAD
    path: kubernetes/synapse-admin
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
